In [ ]:
# array of num
import numpy as np
arr=np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# 3x3 array of 0
import numpy as np
arr=np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 4x4 array
import numpy as np
arr=np.full((4,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# array of even numbers
import numpy as np
arr=np.arange(10, 31)
even=arr[arr % 2==0]
print(even)

[10 12 14 16 18 20 22 24 26 28 30]


In [ ]:
# identity matrix
import numpy as np
arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# shape, size, datatype
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print("shape is: ", arr.shape)
print("size is", arr.size)
print("data type is", arr.dtype)

shape is:  (2, 3)
size is 6
data type is int64


In [ ]:
# reshape array
arr=np.arange(1,13)
new=arr.reshape(3,4)
print(new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# greater than 50
arr = np.array([10, 60, 45, 80, 30, 90])
new=arr[arr>50]
print(new)

[60 80 90]


In [ ]:
# mean, median, std
arr = np.array([5, 10, 15, 20, 25])
print("mean is: ", np.mean(arr))
print("median is", np.median(arr))
print("std is: ", np.std(arr))

mean is:  15.0
median is 15.0
std is:  7.0710678118654755


In [ ]:
# adding two arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print("sum is", a+b)
print("sum is", np.add(a,b))

sum is [5 7 9]
sum is [5 7 9]


In [ ]:
# max, min in random arr
arr=np.random.rand(3,3)
print(arr)
print("max value is: ", np.max(arr))
print("min value is", np.min(arr))

[[0.31112007 0.14297913 0.65181667]
 [0.00551838 0.20901298 0.3997602 ]
 [0.25334356 0.39833907 0.59125344]]
max value is:  0.6518166707112474
min value is 0.005518383817821437


In [ ]:
# sorting array
arr = np.array([12, 4, 7, 1, 9])
print("sorted array is:", np.sort(arr))

sorted array is: [ 1  4  7  9 12]


In [ ]:
# replacing all -ve num
arr = np.array([3, -1, 5, -7, 8])
arr[arr < 0]=0
print("replaced: ", arr)

replaced:  [3 0 5 0 8]
