In [ ]:
# numpy array using python list
import numpy as np
arr=np.array([1,2,3,4,5])
print("array using list: ",arr)

# creating array using arange method
arr_2=np.arange(1,11,2)
print("array using arange: ",arr_2)


#using linespace method
arr_3=np.linspace(0,1,3)
print("array using linespace",arr_3)

array using list:  [1 2 3 4 5]
array using arange:  [1 3 5 7 9]
array using linespace [0.  0.5 1. ]


In [ ]:
# creating a 2d array by lists of lists
arr_list=np.array([[1,2,3,4], [5,6,7,8], [11,22,33,44]])
print(arr_list)


# creatiig 2d using reshape method
arrays=np.array([1,2,3,4])
new_arr=arrays.reshape(2,2)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]
[[1 2]
 [3 4]]


In [ ]:
#create array using list
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

# using arange
arr_2=np.arange(1,11,2)
print(arr_2)

# usind linspace
arr_3=np.linspace(0,2,6)
print(arr_3)


# creating 2d array using list
arr_4=np.array([[1,2,3,4], [1,2,3,4], [1,2,3,4]])
print(arr_4)


#using arange
arry=np.array([1,2,3,4,5,6,7,8])
new=arry.reshape(2,4)
print(new)



[1 2 3 4]
[1 3 5 7 9]
[0.  0.4 0.8 1.2 1.6 2. ]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
arr2=np.array([[1,2,3], [4,5,6]])

print("array is", arr2)

print("shape tells no of rows and columns", arr2.shape)
print("typr tells data type", arr2.dtype)
print("ndim tells number of dimension", arr2.ndim)
print("size tells toytal elements", arr2.size)

array is [[1 2 3]
 [4 5 6]]
shape tells no of rows and columns (2, 3)
typr tells data type int64
ndim tells number of dimension 2
size tells toytal elements 6


In [ ]:
arr2=np.array([[1,2,3], [44,55,66], [21,31,41]])

print(arr2[1: , 0:2])
print(arr2[2,0])

[[44 55]
 [21 31]]
21


In [ ]:
new=np.array([11,22,33,44])

reshaped=(new.reshape(2,2))
print("reshaped array is: ", reshaped)

transposed=reshaped.transpose()
print(transposed)

new.sort()
print(new)

max_index=reshaped.argmax()
print(max_index)

min_index=reshaped.argmin()
print(min_index)



reshaped array is:  [[11 22]
 [33 44]]
[[11 33]
 [22 44]]
[11 22 33 44]
3
0


In [ ]:
first=np.array([1,2,3,4,5])
second=np.array([1,4,3,8,5])

print(first + second)
print(first - second)
print(first * second)
print(first // second)
print(first % second)


print(first == second)
print(first != second)
print(first > second)
print(first <= second)

[ 2  6  6 12 10]
[ 0 -2  0 -4  0]
[ 1  8  9 32 25]
[1 0 1 0 1]
[0 2 0 4 0]
[ True False  True False  True]
[False  True False  True False]
[False False False False False]
[ True  True  True  True  True]


In [ ]:
first=np.array([1,2,3,4,5])
second=np.array([1,4,3,8,5])

#searching
new=np.where(first==2)
print("where result gives index", new)

# concatenate
next=np.concatenate((first, second))
print(next)

# filter
n=first[first > 1]
print(n)

ne=np.exp2(first)
print(ne)

where result gives index (array([1]),)
[1 2 3 4 5 1 4 3 8 5]
[2 3 4 5]
[ 2.  4.  8. 16. 32.]


In [ ]:
print("special arays: ")
print("array containing all zeros: ", np.zeros((2,3)))
print("array containing all one: ", np.ones((2,2)))
print("identity matrix: ", np.eye(3))
print("array containing random numbers", np.random.rand(2,3))
print("line space", np.linspace(1,10,3))

special arays: 
array containing all zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
array containing all one:  [[1. 1.]
 [1. 1.]]
identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
array containing random numbers [[0.51471371 0.69089755 0.84271824]
 [0.58807652 0.26224831 0.61425461]]
line space [ 1.   5.5 10. ]


In [ ]:
# statistical values:
arr=np.array([[1,2,3,4], [5,6,7,8]])
print("mean is: ", np.mean(arr))
print("median is: ", np.median(arr))
print("min value in arr is: ", np.min(arr))
print("max value in is: ", np.max(arr))
print("sum is: ", np.sum(arr))

mean is:  4.5
median is:  4.5
min value in arr is:  1
max value in is:  8
sum is:  36


In [ ]:
import numpy as np
arr_1=np.array([[1,2], [5,6]])
arr_2=np.array([11,22,33,44])

print("multiply by 3: ", arr_1*3)
print("plus 2", arr_1 + 2)


print(np.linalg.det(arr_1)) # .inv   ,.eig       np.trace

arr_3=np.array([[[1,2,3], [4,5,6], [2,5,7]]])
new=arr_3.flatten()
print(new)


n=arr_3[arr_3>2]
print(n)


multiply by 3:  [[ 3  6]
 [15 18]]
plus 2 [[3 4]
 [7 8]]
-3.999999999999999
[1 2 3 4 5 6 2 5 7]
[3 4 5 6 5 7]


In [ ]:
import time
n=1000000

list_1=list(range(n))
lisy_2=list(range(n))

start_time=time.time()
result=[x + y for x , y in zip(list_1, lisy_2)]
end_time=time.time()
print("list takes times: ", round(end_time-start_time,4), "seconds")

import numpy as np
arr_1=np.arange(n)
arr_2=np.arange(n)
start_time=time.time()
result=arr_1 + arr_2
end_time=time.time()
print("array takes time", round(end_time - start_time, 4), "seconds" )


list takes times:  0.083 seconds
array takes time 0.0192 seconds


In [ ]:
import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
arr=np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr=np.linspace(1, 10, 6)
print(arr)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [ ]:
# arr=np.array([[1,2,3,4], [5,6,7,8], [11,22,33,44]])
# arr.sort(axis=None)
# des=arr[:, ::-1]
# print(des)


arr = np.array([[1,2,3,4], [5,6,7,8], [11,22,33,44]])
arr_desc = np.sort(arr, axis=None)[::-1]
print(arr_desc)

arr_sorted = arr[np.sum(arr, axis=1).argsort()[::-1]]
print(arr_sorted)




[44 33 22 11  8  7  6  5  4  3  2  1]
[[11 22 33 44]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr = np.array([[1,2,3,0], [5,6,7,8], [11,22,33,44]])
print(arr.transpose())
print(arr.argmax())
print(arr.argmin())
print(arr.argsort())

[[ 1  5 11]
 [ 2  6 22]
 [ 3  7 33]
 [ 0  8 44]]
11
3
[[3 0 1 2]
 [0 1 2 3]
 [0 1 2 3]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
print(np.random.rand(3, 3,3))

[[[0.7788795  0.07189966 0.34880646]
  [0.27559537 0.07511313 0.48268358]
  [0.90936452 0.42275165 0.25299298]]

 [[0.13049967 0.61342979 0.77735653]
  [0.92181657 0.89728119 0.69172169]
  [0.57589947 0.55735005 0.58532072]]

 [[0.68989944 0.30797512 0.37613797]
  [0.7097651  0.3323932  0.23298655]
  [0.15438188 0.95437471 0.35277812]]]


In [ ]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d.flatten())

[1 2 3 4 5 6 7 8 9]


In [ ]:
import time
n=100000

arr=np.arange(n)
arr2=np.arange(n)
start_time=time.time()
result=arr+arr2
end_time=time.time()
print("array takes: ", end_time-start_time, "seconds")

list_1=list(range(n))
list_2=list(range(n))
start=time.time()
result=[x + y for x , y in zip(list_1 , list_2)]
end=time.time()
print("list takes", end-start, "seconds")



array takes:  0.0004031658172607422 seconds
list takes 0.006128787994384766 seconds
